export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: 'route.dashboard',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: 'route.workbench',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 101,
    pid: 1,
  },
  {
    name: 'monitor',
    path: '/dashboard/monitor',
    title: 'route.monitor',
    requiresAuth: true,
    icon: 'icon-park-outline:anchor',
    menuType: 'page',
    componentPath: '/dashboard/monitor/index.vue',
    id: 102,
    pid: 1,
  },
  {
    name: 'multi',
    path: '/multi',
    title: 'route.multi',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    menuType: 'dir',
    componentPath: null,
    id: 2,
    pid: null,
  },
  {
    name: 'multi2',
    path: '/multi/multi-2',
    title: 'route.multi2',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    menuType: 'page',
    componentPath: '/demo/multi/multi-2/index.vue',
    id: 201,
    pid: 2,
  },
  {
    name: 'multi2-detail',
    path: '/multi/multi-2/detail',
    title: 'route.multi2Detail',
    requiresAuth: false,
    icon: 'icon-park-outline:list',
    hide: true,
    activeMenu: '/multi/multi-2',
    menuType: 'page',
    componentPath: '/demo/multi/multi-2/detail/index.vue',
    id: 20101,
    pid: 2,
  },
  {
    name: 'multi3',
    path: '/multi/multi-3',
    title: 'route.multi3',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    menuType: 'dir',
    componentPath: null,
    id: 202,
    pid: 2,
  },
  {
    name: 'multi4',
    path: '/multi/multi-3/multi-4',
    title: 'route.multi4',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/demo/multi/multi-3/multi-4/index.vue',
    id: 20201,
    pid: 202,
  },
  {
    name: 'list',
    path: '/list',
    title: 'route.list',
    requiresAuth: true,
    icon: 'icon-park-outline:list-two',
    menuType: 'dir',
    componentPath: null,
    id: 3,
    pid: null,
  },
  {
    name: 'commonList',
    path: '/list/common-list',
    title: 'route.commonList',
    requiresAuth: true,
    icon: 'icon-park-outline:list-view',
    componentPath: '/demo/list/common-list/index.vue',
    id: 301,
    pid: 3,
  },
  {
    name: 'cardList',
    path: '/list/card-list',
    title: 'route.cardList',
    requiresAuth: true,
    icon: 'icon-park-outline:view-grid-list',
    componentPath: '/demo/list/card-list/index.vue',
    id: 302,
    pid: 3,
  },
  {
    name: 'draggableList',
    path: '/list/draggable-list',
    title: 'route.draggableList',
    requiresAuth: true,
    icon: 'icon-park-outline:menu-fold',
    componentPath: '/demo/list/draggable-list/index.vue',
    id: 303,
    pid: 3,
  },
  {
    name: 'demo',
    path: '/demo',
    title: 'route.demo',
    requiresAuth: true,
    icon: 'icon-park-outline:application-one',
    menuType: 'dir',
    componentPath: null,
    id: 4,
    pid: null,
  },
  {
    name: 'fetch',
    path: '/demo/fetch',
    title: 'route.fetch',
    requiresAuth: true,
    icon: 'icon-park-outline:international',
    componentPath: '/demo/fetch/index.vue',
    id: 401,
    pid: 4,
  },
  {
    name: 'echarts',
    path: '/demo/echarts',
    title: 'route.echarts',
    requiresAuth: true,
    icon: 'icon-park-outline:chart-proportion',
    componentPath: '/demo/echarts/index.vue',
    id: 402,
    pid: 4,
  },
  {
    name: 'map',
    path: '/demo/map',
    title: 'route.map',
    requiresAuth: true,
    icon: 'carbon:map',
    keepAlive: true,
    componentPath: '/demo/map/index.vue',
    id: 403,
    pid: 4,
  },
  {
    name: 'editor',
    path: '/demo/editor',
    title: 'route.editor',
    requiresAuth: true,
    icon: 'icon-park-outline:editor',
    menuType: 'dir',
    componentPath: null,
    id: 404,
    pid: 4,
  },
  {
    name: 'editorMd',
    path: '/demo/editor/md',
    title: 'route.editorMd',
    requiresAuth: true,
    icon: 'ri:markdown-line',
    componentPath: '/demo/editor/md/index.vue',
    id: 40401,
    pid: 404,
  },
  {
    name: 'editorRich',
    path: '/demo/editor/rich',
    title: 'route.editorRich',
    requiresAuth: true,
    icon: 'icon-park-outline:edit-one',
    componentPath: '/demo/editor/rich/index.vue',
    id: 40402,
    pid: 404,
  },
  {
    name: 'clipboard',
    path: '/demo/clipboard',
    title: 'route.clipboard',
    requiresAuth: true,
    icon: 'icon-park-outline:clipboard',
    componentPath: '/demo/clipboard/index.vue',
    id: 405,
    pid: 4,
  },
  {
    name: 'icons',
    path: '/demo/icons',
    title: 'route.icons',
    requiresAuth: true,
    icon: 'local:cool',
    componentPath: '/demo/icons/index.vue',
    id: 406,
    pid: 4,
  },
  {
    name: 'QRCode',
    path: '/demo/qr-code',
    title: 'route.QRCode',
    requiresAuth: true,
    icon: 'icon-park-outline:two-dimensional-code',
    componentPath: '/demo/qr-code/index.vue',
    id: 407,
    pid: 4,
  },
  {
    name: 'cascader',
    path: '/demo/cascader',
    title: 'route.cascader',
    requiresAuth: true,
    icon: 'icon-park-outline:add-subset',
    componentPath: '/demo/cascader/index.vue',
    id: 408,
    pid: 4,
  },
  {
    name: 'documents',
    path: '/documents',
    title: 'route.documents',
    requiresAuth: true,
    icon: 'icon-park-outline:file-doc',
    menuType: 'dir',
    componentPath: null,
    id: 5,
    pid: null,
  },
  {
    name: 'documentsVue',
    path: '/documents/vue',
    title: 'route.documentsVue',
    requiresAuth: true,
    icon: 'logos:vue',
    componentPath: '/demo/documents/vue/index.vue',
    id: 501,
    pid: 5,
  },
  {
    name: 'documentsVite',
    path: '/documents/vite',
    title: 'route.documentsVite',
    requiresAuth: true,
    icon: 'logos:vitejs',
    componentPath: '/demo/documents/vite/index.vue',
    id: 502,
    pid: 5,
  },
  {
    name: 'documentsVueuse',
    path: '/documents/vue-use',
    title: 'route.documentsVueuse',
    requiresAuth: true,
    icon: 'logos:vueuse',
    href: 'https://vueuse.org/guide/',
    componentPath: 'null',
    id: 503,
    pid: 5,
  },

  {
    name: 'documentsNova',
    path: '/documents/nova',
    title: 'route.documentsNova',
    requiresAuth: true,
    icon: 'local:logo',
    href: 'https://nova-admin-docs.netlify.app/',
    componentPath: '2333333',
    id: 504,
    pid: 5,
  },
  {
    name: 'documentsPublic',
    path: '/documents/public',
    title: 'route.documentsPublic',
    requiresAuth: true,
    icon: 'local:logo',
    href: '/public',
    componentPath: 'null',
    id: 505,
    pid: 5,
  },
  {
    name: 'setting',
    path: '/setting',
    title: 'route.setting',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 7,
    pid: null,
  },
  {
    name: 'accountSetting',
    path: '/setting/account',
    title: 'route.accountSetting',
    requiresAuth: true,
    icon: 'icon-park-outline:every-user',
    componentPath: '/setting/account/index.vue',
    id: 701,
    pid: 7,
  },
  {
    name: 'about',
    path: '/about',
    title: 'route.about',
    requiresAuth: true,
    icon: 'icon-park-outline:info',
    componentPath: '/demo/about/index.vue',
    id: 8,
    pid: null,
  },
  {
    name: 'userCenter',
    path: '/user-center',
    title: 'route.userCenter',
    requiresAuth: true,
    hide: true,
    icon: 'carbon:user-avatar-filled-alt',
    componentPath: '/build-in/user-center/index.vue',
    id: 999,
    pid: null,
  },

]
