package plugins

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// AutoRegisterPlugins 自动扫描并注册插件
// 扫描 plugins 目录下的所有子目录，查找 plugin.go 文件
func AutoRegisterPlugins(mgr *Manager, pluginDir string) error {
	// 获取插件目录的绝对路径
	absPath, err := filepath.Abs(pluginDir)
	if err != nil {
		return fmt.Errorf("无法获取插件目录路径: %v", err)
	}

	// 扫描插件目录
	entries, err := ioutil.ReadDir(absPath)
	if err != nil {
		return fmt.Errorf("无法读取插件目录: %v", err)
	}

	loadedCount := 0
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		pluginName := entry.Name()
		pluginPath := filepath.Join(absPath, pluginName)

		// 检查是否存在 plugin.go
		pluginFile := filepath.Join(pluginPath, "plugin.go")
		if _, err := os.Stat(pluginFile); os.IsNotExist(err) {
			continue
		}

		log.Printf("[Plugin] 发现插件: %s", pluginName)
		loadedCount++
	}

	if loadedCount > 0 {
		log.Printf("[Plugin] 共发现 %d 个待注册插件", loadedCount)
	}

	return nil
}

// GeneratePluginRegistryFile 生成插件注册代码文件
// 这个函数用于构建时自动生成插件注册代码
func GeneratePluginRegistryFile(pluginDir string, outputFile string) error {
	// 获取插件目录的绝对路径
	absPath, err := filepath.Abs(pluginDir)
	if err != nil {
		return fmt.Errorf("无法获取插件目录路径: %v", err)
	}

	// 扫描插件目录
	entries, err := ioutil.ReadDir(absPath)
	if err != nil {
		return fmt.Errorf("无法读取插件目录: %v", err)
	}

	var plugins []struct {
		Name string
		Path string
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		pluginName := entry.Name()
		pluginPath := filepath.Join(absPath, pluginName)

		// 检查是否存在 plugin.go
		pluginFile := filepath.Join(pluginPath, "plugin.go")
		if _, err := os.Stat(pluginFile); os.IsNotExist(err) {
			continue
		}

		plugins = append(plugins, struct {
			Name string
			Path string
		}{
			Name: pluginName,
			Path: "fst/backend/app/plugins/" + pluginName,
		})
	}

	// 生成代码
	var code strings.Builder
	code.WriteString("// Code generated by plugin auto-register. DO NOT EDIT.\n")
	code.WriteString("// +build !ignore_autogen\n\n")
	code.WriteString("package plugins\n\n")
	code.WriteString("import (\n")
	for _, p := range plugins {
		code.WriteString(fmt.Sprintf("\t_ \"%s\"\n", p.Path))
	}
	code.WriteString(")\n\n")

	// 写入文件
	return ioutil.WriteFile(outputFile, []byte(code.String()), 0644)
}
