// Package middleware 提供 Scalar API 文档的运行时改写中间件。
package middleware

// ModelNameCN 模型名英文（Go 类型名）-> 中文翻译映射。
// 新增模型时在这里加一行即可，Swagger 文档中的模型名会自动翻译为中文。
var ModelNameCN = map[string]string{
	"AdminCompleteOrderRequest":   "管理端补单请求",
	"AdminResolveExceptionRequest": "管理端订单异常处理请求",
	"AdminUserDetailResponse":     "管理端用户详情响应",
	"AdminUserRealnameSummary":    "管理端用户实名认证摘要",
	"BatchUpdateSettingsRequest":  "批量更新系统设置请求",
	"CreateSettingRequest":        "创建系统设置请求",
	"EmailPreviewRequest":         "邮件内容预览请求",
	"EmailSendTestRequest":        "邮件发送测试请求",
	"EmailTemplateUpdateRequest":  "邮件模板更新请求",
	"ReviewRealnameRequest":       "实名认证审核请求",
	"SMSPreviewRequest":           "短信内容预览请求",
	"SMSSendTestRequest":          "短信发送测试请求",
	"SMSTemplateUpdateRequest":    "短信模板更新请求",
	"SettingsListResponse":        "系统设置列表响应",
	"UpdateSettingMetaRequest":    "更新系统设置元信息请求",
	"UpdateSettingRequest":        "更新系统设置请求",
	"AppConfigResponse":           "应用配置响应",
	"DialCountriesResponse":       "国际区号列表响应",
	"LoginRequest":                "登录请求",
	"PhoneCountryResponse":        "手机号国家区号响应",
	"RefreshTokenRequest":         "刷新令牌请求",
	"RegisterRequest":             "注册请求",
	"ResetEmailRequest":           "重置邮箱请求",
	"ResetPasswordConfirmRequest": "重置密码确认请求",
	"SendCodeRequest":             "发送验证码请求",
	"ChangePasswordRequest":       "修改密码请求",
	"CreateOrderRequest":          "创建订单请求",
	"DeactivateAccountRequest":    "注销账号请求",
	"ProfileRealnameSummary":      "用户实名认证摘要",
	"ProfileResponse":             "用户资料响应",
	"SendEmailCodeRequest":        "发送邮箱验证码请求",
	"SendPhoneCodeRequest":        "发送手机验证码请求",
	"SubmitRealnameRequest":       "提交实名认证请求",
	"UpdateProfileRequest":        "更新个人资料请求",
	"UpdateSettingsRequest":       "更新用户设置请求",
	"VerifyEmailChangeRequest":    "验证邮箱变更请求",
	"VerifyPhoneChangeRequest":    "验证手机号变更请求",
	"AdminUserListItem":           "管理端用户列表项",
	"UserCreateRequest":           "创建用户请求",
	"UserUpdateRequest":           "更新用户请求",
	"SettingDTO":                  "系统设置 DTO",
	"SettingsGroup":               "设置分组",
	"DialCountry":                 "国际区号",
	"Response":                    "通用响应",
}